// src/tray.rs — Systray icon and menu
// Last modified: 2026-04-12

use tray_icon::{
    menu::{CheckMenuItem, Menu, MenuEvent, MenuId, MenuItem, PredefinedMenuItem, Submenu},
    Icon, TrayIcon, TrayIconBuilder, TrayIconEvent,
};
use windows::Win32::System::Registry::{
    RegCreateKeyExW, RegDeleteValueW, RegQueryValueExW, RegSetValueExW,
    HKEY_CURRENT_USER, KEY_READ, KEY_WRITE, REG_OPTION_NON_VOLATILE, REG_SZ,
};
use windows::core::PCWSTR;

// ── Icon loading ─────────────────────────────────────────────────────────────
//
// The tray and the settings-window title bar both use a pre-rendered .ico
// file at `assets/joro_icon.ico` (connected) / `assets/joro_icon_disconnected.ico`.
// These are regenerated by running `python assets/gen_icon.py`. They're
// multi-size ICOs so Windows picks the right resolution per DPI.
//
// The ICO files are embedded at compile time via `include_bytes!` so the
// daemon has no file I/O dependency at runtime. If we ever want live icon
// editing we can switch to Icon::from_path().

// Legacy hand-drawn PIL ICOs — kept as fallback because they contain
// every size from 16px to 256px and work well for the window title-bar.
pub const ICON_CONNECTED: &[u8] = include_bytes!("../assets/joro_icon.ico");
pub const ICON_DISCONNECTED: &[u8] = include_bytes!("../assets/joro_icon_disconnected.ico");

// Authoritative tray icon sources: 32x32 PNGs derived from Microsoft's
// On-Screen Keyboard (osk.exe) icon. The hand-drawn PIL versions kept
// looking pixelated at 16px no matter what we tried, so we post-process
// osk's built-in keyboard glyph into our connected / disconnected
// variants via `assets/gen_icon.py` + `assets/extract_osk_icon.ps1`.
// See those scripts for the license note.
pub const TRAY_PNG_CONNECTED: &[u8] = include_bytes!("../assets/joro_icon_32.png");
pub const TRAY_PNG_DISCONNECTED: &[u8] = include_bytes!("../assets/joro_icon_disconnected_32.png");

/// Decode the embedded connected icon into raw RGBA + dimensions, for use
/// as the window title-bar icon (winit::window::Icon::from_rgba).
/// Prefers the 32x32 osk-derived PNG so the title-bar matches the tray
/// icon visually; falls back to the legacy multi-size ICO if decode
/// fails.
pub fn window_icon_rgba() -> Option<(Vec<u8>, u32, u32)> {
    if let Ok(img) =
        image::load_from_memory_with_format(TRAY_PNG_CONNECTED, image::ImageFormat::Png)
    {
        let rgba = img.to_rgba8();
        let (w, h) = rgba.dimensions();
        return Some((rgba.into_raw(), w, h));
    }
    let img = image::load_from_memory_with_format(ICON_CONNECTED, image::ImageFormat::Ico)
        .ok()?
        .to_rgba8();
    let (w, h) = img.dimensions();
    Some((img.into_raw(), w, h))
}

/// Decode one of the embedded ICOs into an RGBA image via the `image` crate,
/// then hand it to tray-icon as a raw Icon. Picks the 32x32 frame if present,
/// otherwise the largest frame <= 64x64.
fn load_icon_from_ico(bytes: &[u8]) -> Option<Icon> {
    // image crate handles ICO decoding — gives us the largest frame by default.
    let img = image::load_from_memory_with_format(bytes, image::ImageFormat::Ico)
        .ok()?
        .to_rgba8();
    let (w, h) = img.dimensions();
    Icon::from_rgba(img.into_raw(), w, h).ok()
}

/// Return a tray icon reflecting the current connection state. Loads
/// the dedicated 32x32 PNG (not the multi-size ICO) so Windows does a
/// single sharp downscale from a hand-rendered source to whatever the
/// current tray display size is. Falls back to runtime pixel drawing
/// if PNG decode fails (shouldn't happen in practice).
pub fn create_icon(connected: bool) -> Icon {
    let png_bytes = if connected { TRAY_PNG_CONNECTED } else { TRAY_PNG_DISCONNECTED };
    if let Ok(img) = image::load_from_memory_with_format(png_bytes, image::ImageFormat::Png) {
        let rgba = img.to_rgba8();
        let (w, h) = rgba.dimensions();
        if let Ok(icon) = Icon::from_rgba(rgba.into_raw(), w, h) {
            return icon;
        }
    }
    // Legacy fallback path — ICO-based loader, then raw pixel draw.
    let bytes = if connected { ICON_CONNECTED } else { ICON_DISCONNECTED };
    if let Some(icon) = load_icon_from_ico(bytes) {
        return icon;
    }
    eprintln!("Warning: failed to load embedded icon, using runtime pixel draw");
    create_icon_runtime_fallback(connected)
}

/// Runtime-drawn fallback 32x32 keyboard icon (used if the embedded ICO
/// fails to decode for some reason). Simple enough to never break.
fn create_icon_runtime_fallback(connected: bool) -> Icon {
    const SIZE: usize = 32;
    let mut rgba = vec![0u8; SIZE * SIZE * 4];

    let outline: (u8, u8, u8, u8) = if connected {
        (255, 255, 255, 0xFF)
    } else {
        (150, 150, 150, 0xFF)
    };
    let body: (u8, u8, u8, u8) = (20, 20, 20, 0xFF);
    let key: (u8, u8, u8, u8) = if connected {
        (235, 235, 235, 0xFF)
    } else {
        (120, 120, 120, 0xFF)
    };

    let set = |rgba: &mut [u8], x: i32, y: i32, c: (u8, u8, u8, u8)| {
        if x < 0 || y < 0 || x >= SIZE as i32 || y >= SIZE as i32 {
            return;
        }
        let idx = ((y as usize) * SIZE + x as usize) * 4;
        rgba[idx] = c.0;
        rgba[idx + 1] = c.1;
        rgba[idx + 2] = c.2;
        rgba[idx + 3] = c.3;
    };

    let fill_rect = |rgba: &mut [u8], x1: i32, y1: i32, x2: i32, y2: i32, c: (u8, u8, u8, u8)| {
        for y in y1..=y2 {
            for x in x1..=x2 {
                set(rgba, x, y, c);
            }
        }
    };

    // Keyboard outer rectangle: x=1..30, y=6..26 (30 wide x 21 tall)
    let (ox1, oy1, ox2, oy2) = (1_i32, 6, 30, 26);

    // Body fill (dark interior)
    fill_rect(&mut rgba, ox1 + 1, oy1 + 1, ox2 - 1, oy2 - 1, body);

    // Outline (1px border)
    for x in ox1..=ox2 {
        set(&mut rgba, x, oy1, outline);
        set(&mut rgba, x, oy2, outline);
    }
    for y in oy1..=oy2 {
        set(&mut rgba, ox1, y, outline);
        set(&mut rgba, ox2, y, outline);
    }
    // Soften corners — remove the 4 corner pixels so it reads as rounded
    set(&mut rgba, ox1, oy1, (0, 0, 0, 0));
    set(&mut rgba, ox2, oy1, (0, 0, 0, 0));
    set(&mut rgba, ox1, oy2, (0, 0, 0, 0));
    set(&mut rgba, ox2, oy2, (0, 0, 0, 0));

    // 3 rows of 6 small key blocks (3x3 each)
    // Interior usable area: x=3..28 (26 wide), y=8..24 (17 tall)
    // Keys at y=9, 13, 17 (top-left of each key), each 3x3
    // Columns at x = 3, 7, 11, 15, 19, 23 (3-wide with 1px gap)
    let cols = [3_i32, 7, 11, 15, 19, 23];
    let rows = [9_i32, 13];
    for &ky in &rows {
        for &kx in &cols {
            fill_rect(&mut rgba, kx, ky, kx + 2, ky + 2, key);
        }
    }

    // Bottom row: wide spacebar (3 tall, spans from col[0] to col[5]+2)
    let sb_y = 18;
    fill_rect(&mut rgba, 5, sb_y, 22, sb_y + 2, key);

    // Disconnected state: red LED indicator above the keyboard (top-right)
    if !connected {
        let red: (u8, u8, u8, u8) = (0xFF, 0x40, 0x40, 0xFF);
        let red_dim: (u8, u8, u8, u8) = (0xC0, 0x20, 0x20, 0xFF);
        // 4x4 LED dot with a slight fade at corners
        fill_rect(&mut rgba, 24, 1, 27, 4, red);
        // Corner softening
        set(&mut rgba, 24, 1, red_dim);
        set(&mut rgba, 27, 1, red_dim);
        set(&mut rgba, 24, 4, red_dim);
        set(&mut rgba, 27, 4, red_dim);
    }

    Icon::from_rgba(rgba, SIZE as u32, SIZE as u32)
        .expect("Failed to create tray icon from RGBA data")
}

// ── Preset tables ────────────────────────────────────────────────────────────

/// Color presets: (label, hex_string_with_hash, (r,g,b)).
pub const COLOR_PRESETS: &[(&str, &str, (u8, u8, u8))] = &[
    ("Red",    "#FF0000", (0xFF, 0x00, 0x00)),
    ("Orange", "#FF8800", (0xFF, 0x88, 0x00)),
    ("Yellow", "#FFFF00", (0xFF, 0xFF, 0x00)),
    ("Green",  "#00CC44", (0x00, 0xCC, 0x44)),
    ("Cyan",   "#00FFFF", (0x00, 0xFF, 0xFF)),
    ("Blue",   "#0044FF", (0x00, 0x44, 0xFF)),
    ("Purple", "#AA00FF", (0xAA, 0x00, 0xFF)),
    ("White",  "#FFFFFF", (0xFF, 0xFF, 0xFF)),
];

/// Brightness presets: (label, level 0-255).
pub const BRIGHTNESS_PRESETS: &[(&str, u8)] = &[
    ("25%",  64),
    ("50%", 128),
    ("75%", 192),
    ("100%", 255),
];

/// Effect modes: (label, config mode string).
pub const EFFECT_PRESETS: &[(&str, &str)] = &[
    ("Static",    "static"),
    ("Breathing", "breathing"),
    ("Spectrum",  "spectrum"),
];

// ── JoroTray ──────────────────────────────────────────────────────────────────

pub struct JoroTray {
    _tray: TrayIcon,
    pub menu_settings_id: MenuId,
    pub menu_reload_id: MenuId,
    pub menu_open_config_id: MenuId,
    pub menu_autostart_id: MenuId,
    pub menu_quit_id: MenuId,
    /// Parallel to COLOR_PRESETS: (menu id, check item). Indexed lookup.
    color_items: Vec<CheckMenuItem>,
    brightness_items: Vec<CheckMenuItem>,
    effect_items: Vec<CheckMenuItem>,
    status_item: MenuItem,
    firmware_item: MenuItem,
    autostart_item: MenuItem,
}

impl JoroTray {
    pub fn new() -> Self {
        let status_item = MenuItem::new("Razer Joro \u{2014} Disconnected", false, None);
        let firmware_item = MenuItem::new("Firmware: \u{2014}", false, None);
        let settings_item = MenuItem::new("Settings\u{2026}", true, None);
        let reload_item = MenuItem::new("Reload Config", true, None);
        let open_config_item = MenuItem::new("Open Config File", true, None);
        let autostart_label = if is_autostart_enabled() {
            "Autostart: On"
        } else {
            "Autostart: Off"
        };
        let autostart_item = MenuItem::new(autostart_label, true, None);
        let quit_item = MenuItem::new("Quit", true, None);

        let menu_settings_id = settings_item.id().clone();
        let menu_reload_id = reload_item.id().clone();
        let menu_open_config_id = open_config_item.id().clone();
        let menu_autostart_id = autostart_item.id().clone();
        let menu_quit_id = quit_item.id().clone();

        // Color submenu
        let color_items: Vec<CheckMenuItem> = COLOR_PRESETS
            .iter()
            .map(|(label, _, _)| CheckMenuItem::new(*label, true, false, None))
            .collect();
        let color_submenu = Submenu::new("Color", true);
        for item in &color_items {
            let _ = color_submenu.append(item);
        }

        // Brightness submenu
        let brightness_items: Vec<CheckMenuItem> = BRIGHTNESS_PRESETS
            .iter()
            .map(|(label, _)| CheckMenuItem::new(*label, true, false, None))
            .collect();
        let brightness_submenu = Submenu::new("Brightness", true);
        for item in &brightness_items {
            let _ = brightness_submenu.append(item);
        }

        // Effect submenu
        let effect_items: Vec<CheckMenuItem> = EFFECT_PRESETS
            .iter()
            .map(|(label, _)| CheckMenuItem::new(*label, true, false, None))
            .collect();
        let effect_submenu = Submenu::new("Effect", true);
        for item in &effect_items {
            let _ = effect_submenu.append(item);
        }

        let menu = Menu::with_items(&[
            &status_item,
            &firmware_item,
            &PredefinedMenuItem::separator(),
            &color_submenu,
            &brightness_submenu,
            &effect_submenu,
            &PredefinedMenuItem::separator(),
            &settings_item,
            &reload_item,
            &open_config_item,
            &autostart_item,
            &PredefinedMenuItem::separator(),
            &quit_item,
        ])
        .expect("Failed to create tray menu");

        let icon = create_icon(false);

        let tray = TrayIconBuilder::new()
            .with_tooltip("Joro Daemon")
            .with_icon(icon)
            .with_menu(Box::new(menu))
            .with_menu_on_left_click(false) // left-click = settings, right-click = menu
            .build()
            .expect("Failed to create tray icon");

        JoroTray {
            _tray: tray,
            menu_settings_id,
            menu_reload_id,
            menu_open_config_id,
            menu_autostart_id,
            menu_quit_id,
            color_items,
            brightness_items,
            effect_items,
            status_item,
            firmware_item,
            autostart_item,
        }
    }

    /// Find which color preset was clicked. Returns Some((hex, rgb)) if the id
    /// matches one of our color items, else None.
    pub fn match_color(&self, id: &MenuId) -> Option<(&'static str, (u8, u8, u8))> {
        for (i, item) in self.color_items.iter().enumerate() {
            if item.id() == id {
                let (_, hex, rgb) = COLOR_PRESETS[i];
                return Some((hex, rgb));
            }
        }
        None
    }

    /// Find which brightness preset was clicked. Returns the level if matched.
    pub fn match_brightness(&self, id: &MenuId) -> Option<u8> {
        for (i, item) in self.brightness_items.iter().enumerate() {
            if item.id() == id {
                return Some(BRIGHTNESS_PRESETS[i].1);
            }
        }
        None
    }

    /// Find which effect preset was clicked. Returns the mode string if matched.
    pub fn match_effect(&self, id: &MenuId) -> Option<&'static str> {
        for (i, item) in self.effect_items.iter().enumerate() {
            if item.id() == id {
                return Some(EFFECT_PRESETS[i].1);
            }
        }
        None
    }

    /// Update the checkmarks on the submenu items to reflect the current config.
    pub fn sync_check_state(&self, color_hex: &str, brightness: u8, mode: &str) {
        for (i, item) in self.color_items.iter().enumerate() {
            item.set_checked(COLOR_PRESETS[i].1.eq_ignore_ascii_case(color_hex));
        }
        for (i, item) in self.brightness_items.iter().enumerate() {
            // Round-match: closest preset within half a step
            let level = BRIGHTNESS_PRESETS[i].1;
            let checked = brightness.abs_diff(level) <= 16;
            item.set_checked(checked);
        }
        for (i, item) in self.effect_items.iter().enumerate() {
            item.set_checked(EFFECT_PRESETS[i].1.eq_ignore_ascii_case(mode));
        }
    }

    /// Toggle autostart and update the menu label.
    pub fn toggle_autostart(&self) {
        if is_autostart_enabled() {
            disable_autostart();
            self.autostart_item.set_text("Autostart: Off");
            eprintln!("joro-daemon: autostart disabled");
        } else {
            enable_autostart();
            self.autostart_item.set_text("Autostart: On");
            eprintln!("joro-daemon: autostart enabled");
        }
    }

    /// Update the tray icon and menu status items based on connection state.
    pub fn set_connected(
        &mut self,
        connected: bool,
        firmware: Option<&str>,
        transport: Option<&str>,
    ) {
        let icon = create_icon(connected);
        let _ = self._tray.set_icon(Some(icon));

        let status_text = if connected {
            match transport {
                Some(t) => format!("Razer Joro \u{2014} Connected ({})", t),
                None => "Razer Joro \u{2014} Connected".to_string(),
            }
        } else {
            "Razer Joro \u{2014} Disconnected".to_string()
        };
        self.status_item.set_text(status_text);

        let fw_text = match firmware {
            Some(fw) => format!("Firmware: {}", fw),
            None => "Firmware: \u{2014}".to_string(),
        };
        self.firmware_item.set_text(fw_text);
    }
}

// ── Menu event polling ────────────────────────────────────────────────────────

/// Non-blocking poll for a menu event.
pub fn poll_menu_event() -> Option<MenuEvent> {
    MenuEvent::receiver().try_recv().ok()
}

/// Non-blocking poll for a tray-icon mouse event (left/right click, etc.).
pub fn poll_tray_event() -> Option<TrayIconEvent> {
    TrayIconEvent::receiver().try_recv().ok()
}

// ── Autostart (registry) ─────────────────────────────────────────────────────

const RUN_KEY: &str = r"Software\Microsoft\Windows\CurrentVersion\Run";
const VALUE_NAME: &str = "JoroDaemon";

fn run_key_wide() -> Vec<u16> {
    RUN_KEY.encode_utf16().chain(std::iter::once(0)).collect()
}

fn value_name_wide() -> Vec<u16> {
    VALUE_NAME.encode_utf16().chain(std::iter::once(0)).collect()
}

/// Check if autostart registry value exists.
pub fn is_autostart_enabled() -> bool {
    let key_w = run_key_wide();
    let val_w = value_name_wide();
    unsafe {
        let mut hkey = std::mem::zeroed();
        let res = RegCreateKeyExW(
            HKEY_CURRENT_USER,
            PCWSTR(key_w.as_ptr()),
            0,
            None,
            REG_OPTION_NON_VOLATILE,
            KEY_READ,
            None,
            &mut hkey,
            None,
        );
        if res.is_err() {
            return false;
        }
        let exists = RegQueryValueExW(
            hkey,
            PCWSTR(val_w.as_ptr()),
            None,
            None,
            None,
            None,
        ).is_ok();
        let _ = windows::Win32::System::Registry::RegCloseKey(hkey);
        exists
    }
}

/// Set autostart registry value to current exe path.
pub fn enable_autostart() {
    let exe = std::env::current_exe().unwrap_or_default();
    let exe_str = exe.to_string_lossy();
    let exe_w: Vec<u16> = exe_str.encode_utf16().chain(std::iter::once(0)).collect();
    let key_w = run_key_wide();
    let val_w = value_name_wide();

    unsafe {
        let mut hkey = std::mem::zeroed();
        let res = RegCreateKeyExW(
            HKEY_CURRENT_USER,
            PCWSTR(key_w.as_ptr()),
            0,
            None,
            REG_OPTION_NON_VOLATILE,
            KEY_WRITE,
            None,
            &mut hkey,
            None,
        );
        if res.is_err() {
            eprintln!("Warning: failed to open Run registry key");
            return;
        }
        let byte_len = (exe_w.len() * 2) as u32;
        let _ = RegSetValueExW(
            hkey,
            PCWSTR(val_w.as_ptr()),
            0,
            REG_SZ,
            Some(std::slice::from_raw_parts(exe_w.as_ptr() as *const u8, byte_len as usize)),
        );
        let _ = windows::Win32::System::Registry::RegCloseKey(hkey);
    }
}

/// Remove autostart registry value.
pub fn disable_autostart() {
    let key_w = run_key_wide();
    let val_w = value_name_wide();

    unsafe {
        let mut hkey = std::mem::zeroed();
        let res = RegCreateKeyExW(
            HKEY_CURRENT_USER,
            PCWSTR(key_w.as_ptr()),
            0,
            None,
            REG_OPTION_NON_VOLATILE,
            KEY_WRITE,
            None,
            &mut hkey,
            None,
        );
        if res.is_err() {
            return;
        }
        let _ = RegDeleteValueW(hkey, PCWSTR(val_w.as_ptr()));
        let _ = windows::Win32::System::Registry::RegCloseKey(hkey);
    }
}
